name: 'ads-analytics'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel=6.25.0
  - dash=2.11.0
  - dash-bootstrap-components=1.7.1
  - plotly=5.15.0
  - pandas=1.5.3
  - numpy=1.24.2
  - altair==5.3.*
  - vegafusion>=1.5.0
  - vegafusion-python-embed>=1.5.0
  - matplotlib>=3.0.0
  - wordcloud>=1.8.0
  - pip
  - pip:
      - dash-vega-components==0.11.0
      - gunicorn==21.2.*
      - vl-convert-python>=1.3.0